name: BabyLog Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GCP Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set +e
            cd ~/babylog-backend

            echo "▶ Pull"
            git pull origin main

            echo "▶ Build"
            ./gradlew build

            echo "▶ Stop old server"
            pkill -f java || echo "no java process"

            echo "▶ Start new server"
            nohup java -jar build/libs/*.jar > nohup.out 2>&1 &

            echo "✅ Deploy finished successfully"
            true

