name: Deploy BabyLog Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to GCP Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.63.165.174
          username: dkffl2021
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            echo "▶ Move to project directory"
            cd /home/dkffl2021/babylog-backend

            echo "▶ Pull latest code"
            git pull origin main

            echo "▶ Build project"
            ./gradlew clean build -x test

            echo "▶ Restart BabyLog service"
            sudo systemctl restart babylog

            echo "✅ Deploy finished successfully"
